### ISSUE TITLE
File not found for deep learning models

### ISSUE THREAD

**Issue by mcianfrocco** [rsanchezgarc/deepEMhancer#1]
Hello - 

During installation, I ran into an issue for retrieving the latest deep learning models using your download python script or just using wget (see below). 

Is there a typo in the download link address? http://biocomp.cnb.csic.es/deepEMhancer/deepEMhancerModels.zip 

Mike

```
$ deepemhancer --download
DOWNLAODING MODELs from http://biocomp.cnb.csic.es/deepEMhancer/deepEMhancerModels.zip to /home/cosmic2/.local/share/deepEMhancerModels
It may take a while...
Traceback (most recent call last):
  File "/projects/cosmic2/conda/deepEMhancer_env/bin/deepemhancer", line 10, in <module>
    sys.exit(commanLineFun())
  File "/projects/cosmic2/conda/deepEMhancer_env/lib/python3.6/site-packages/deepEMhancer/exeDeepEMhancer.py", line 80, in commanLineFun
    main( ** parseArgs() )
  File "/projects/cosmic2/conda/deepEMhancer_env/lib/python3.6/site-packages/deepEMhancer/cmdParser.py", line 94, in parseArgs
    args = vars(parser.parse_args())
  File "/projects/cosmic2/conda/deepEMhancer_env/lib/python3.6/argparse.py", line 1734, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/projects/cosmic2/conda/deepEMhancer_env/lib/python3.6/argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/projects/cosmic2/conda/deepEMhancer_env/lib/python3.6/argparse.py", line 1972, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/projects/cosmic2/conda/deepEMhancer_env/lib/python3.6/argparse.py", line 1912, in consume_optional
    take_action(action, args, option_string)
  File "/projects/cosmic2/conda/deepEMhancer_env/lib/python3.6/argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "/projects/cosmic2/conda/deepEMhancer_env/lib/python3.6/site-packages/deepEMhancer/cmdParser.py", line 65, in __call__
    raise Exception("It was not possible to download the model")
Exception: It was not possible to download the model
```

```
$ wget http://biocomp.cnb.csic.es/deepEMhancer/deepEMhancerModels.zip /home/cosmic2/.local/share/deepEMhancerModels 
--2020-09-02 11:48:58--  http://biocomp.cnb.csic.es/deepEMhancer/deepEMhancerModels.zip
Resolving biocomp.cnb.csic.es (biocomp.cnb.csic.es)... 150.244.87.24
Connecting to biocomp.cnb.csic.es (biocomp.cnb.csic.es)|150.244.87.24|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-09-02 11:48:59 ERROR 404: Not Found.
```

**Comment by rsanchezgarc** [comment]
Dear Mike,

Thank you very much for letting me know. There is not a problem with the URL but with our server (a configuration error caused by a new site added) . I will try to make it work ASAP.

In the meanwhile, you can use the alternative URL

http://campins.cnb.csic.es/deepEMhancer/deepEMhancerModels.zip

Thanks for your understanding.

**Comment by mcianfrocco** [comment]
Thank you - this worked for me. 

Mike
