### ISSUE TITLE
noiseStats

### ISSUE THREAD

**Issue by jacey7** [rsanchezgarc/deepEMhancer#15]
Hello, I have a really dummy question about normalization. I measured noise from the non-protein area of my map in chimera and the mean was -0.003 and SD is 0.002. When I added the flag --noiseStats -0.003 0.002, it gave me an error (but it was fine without this flag). I wonder if it is because the negative number was recognized as a flag instead of an input. Please let me know if you have any idea how to fix it. Many thanks!

Jiayi 

P.S. Below please see the log file:

[+] Loading singularity  3.8.1  on cn4186 
[+] Loading CUDA Toolkit  10.2.89  ... 
[+] Loading DeepEMhancer  0.13 
WARNING: While bind mounting '/gpfs:/gpfs': destination is already in the mount point list
updating environment to select gpu: [0, 1]
loading model /home/chenj33/.local/share/deepEMhancerModels/production_checkpoints/deepEMhancer_tightTarget.hd5 ... DONE!
DONE!. Shape at 1.00 A/voxel after padding->  (608, 608, 608)
Using TensorFlow backend.
  0%|          | 0/1225 [00:00<?, ?it/s]Neural net inference
Traceback (most recent call last):
  File "/opt/conda/envs/app/bin/deepemhancer", line 10, in <module>
    sys.exit(commanLineFun())
  File "/opt/conda/envs/app/lib/python3.6/site-packages/deepEMhancer/exeDeepEMhancer.py", line 80, in commanLineFun
    main( ** parseArgs() )
  File "/opt/conda/envs/app/lib/python3.6/site-packages/deepEMhancer/exeDeepEMhancer.py", line 73, in main
    voxel_size=boxSize, apply_postprocess_cleaning=cleaningStrengh)
  File "/opt/conda/envs/app/lib/python3.6/site-packages/deepEMhancer/applyProcessVol/processVol.py", line 186, in predict
    batch_y_pred= self.model.predict_on_batch(np.expand_dims(batch_x, axis=-1))
  File "/opt/conda/envs/app/lib/python3.6/site-packages/keras/engine/training.py", line 1274, in predict_on_batch
    outputs = self.predict_function(ins)
  File "/opt/conda/envs/app/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/opt/conda/envs/app/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/opt/conda/envs/app/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1458, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: No algorithm worked!
	 [[{{node replica_0/model_1/conv3d_transpose_4/conv3d_transpose}}]]
  (1) Not found: No algorithm worked!
	 [[{{node replica_0/model_1/conv3d_transpose_4/conv3d_transpose}}]]
	 [[replica_0/model_1/conv3d_21/add/_813]]
0 successful operations.
1 derived errors ignored.

**Comment by rsanchezgarc** [comment]
Dear Jiayi,

In principle, this kind of errors are caused when you get out of GPU memory, and shouldn't be related to the fact that  --noiseStats  was provided with a negative number (with the possible exception that your input is less sparse after the normalization)

In order to decrease GPU memory fingerprint, you could set the -b argument to a smaller number. I would try first with -b 1, since if it does not work with -b 1, it won't work with any larger one.

Appart from that, it is good to set  the TF_FORCE_GPU_ALLOW_GROWTH='true' variable before executing deepemhancer when facing GPU memory problems. You could just export it or directly run the command as follows:

```
TF_FORCE_GPU_ALLOW_GROWTH='true' deepemhancer -p highRes -i  emd_24688.map.gz -o prueba.mrc --noiseStats -0.12 0.03 -b 2
```

I hope it helps.

Ruben
