### ISSUE TITLE
Crash when running deepemhancer

### ISSUE THREAD

**Issue by douweschulte** [rsanchezgarc/deepEMhancer#29]
Deepemhancer seems to start up fine on our machine but crashes after a while. I do not know where to start for debugging is there any pointers you could give me?

We are running deepemhancer `20220530_cu10` through sbgrid on an ubuntu workstation with 4 RTXA4000s.

Thanks in advance!

<details><pre>
douwe@Snijderlab-GPU:/storage-hdd/martas/230206_RSVpostF_1312a/CS-131-2a/J214$ deepemhancer -i J214_004_volume_map_sharp.mrc -o J214_004_volume_map_sharp_DE.mrc --deepLearningModelPath /storage/ssd/deepemhancer/production_checkpoints
updating environment to select gpu: [0]
Using TensorFlow backend.
loading model /storage/ssd/deepemhancer/production_checkpoints/deepEMhancer_tightTarget.hd5 ... DONE!
Automatic radial noise detected beyond 37.0 % of volume side
DONE!. Shape at 1 A/voxel after padding->  (384, 384, 384)
Neural net inference
  0%|                                                                                                                                                                                    | 0/441 [00:00<?, ?it/s]2023-10-16 14:48:17.079997: E tensorflow/stream_executor/cuda/cuda_blas.cc:428] failed to run cuBLAS routine: CUBLAS_STATUS_EXECUTION_FAILED
Traceback (most recent call last):
  File "/programs/x86_64-linux/deepemhancer/20220530_cu10/bin/deepemhancer", line 11, in <module>
    sys.exit(commanLineFun())
  File "/programs/x86_64-linux/deepemhancer/20220530_cu10/miniconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/deepEMhancer/exeDeepEMhancer.py", line 80, in commanLineFun
    main( ** parseArgs() )
  File "/programs/x86_64-linux/deepemhancer/20220530_cu10/miniconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/deepEMhancer/exeDeepEMhancer.py", line 73, in main
    voxel_size=boxSize, apply_postprocess_cleaning=cleaningStrengh)
  File "/programs/x86_64-linux/deepemhancer/20220530_cu10/miniconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/deepEMhancer/applyProcessVol/processVol.py", line 186, in predict
    batch_y_pred= self.model.predict_on_batch(np.expand_dims(batch_x, axis=-1))
  File "/programs/x86_64-linux/deepemhancer/20220530_cu10/miniconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/keras/engine/training.py", line 1274, in predict_on_batch
    outputs = self.predict_function(ins)
  File "/programs/x86_64-linux/deepemhancer/20220530_cu10/miniconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/programs/x86_64-linux/deepemhancer/20220530_cu10/miniconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/programs/x86_64-linux/deepemhancer/20220530_cu10/miniconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1458, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Blas SGEMM launch failed : m=2097152, n=1, k=8
         [[{{node conv3d_21/convolution}}]]
  (1) Internal: Blas SGEMM launch failed : m=2097152, n=1, k=8
         [[{{node conv3d_21/convolution}}]]
         [[activation_10/Identity/_609]]
0 successful operations.
0 derived errors ignored.
  0%|                                                                                                                                                                                    | 0/441 [12:4douwe@Snijddouwe@Snijderlab-GPU:/storage-hdd/martas/230206_RSVpostF_1312a/CS-131-2a/J214$
</pre></details>

**Comment by rsanchezgarc** [comment]
Hi, there could be several reasons for the error message.

First, can you try to use batch size 1 (-b 1) and only one GPU (-g 1)?

Can you also try to export the following env variable? 
```
export TF_FORCE_GPU_ALLOW_GROWTH='true'
```

If it does not work, the 20220530_cu10 version may be incompatible with your GPU. So, I would encourage you to try a newer version. Can you run 
```
python -c "import tensorflow as tf; print([d.name for d in tf.config.list_physical_devices('GPU')])"
``` 
to check if this is the case?

**Comment by douweschulte** [comment]
Thanks for the swift reply! With the changes you mentioned I still get a similar error:
<details><pre>
douwe@Snijderlab-GPU:/storage-hdd/martas/230206_RSVpostF_1312a/CS-131-2a/J214$ export TF_FORCE_GPU_ALLOW_GROWTH='true'
douwe@Snijderlab-GPU:/storage-hdd/martas/230206_RSVpostF_1312a/CS-131-2a/J214$ deepemhancer -i J214_004_volume_map_sharp.mrc -o J214_004_volume_map_sharp_DE.mrc --deepLearningModelPath /storage/ssd/deepemhancer/production_checkpoints -b 1 -g 1
bash: /programs/x86_64-linux/deepemhancer/20220530_cu10/lib/libtinfo.so.6: no version information available (required by bash)
updating environment to select gpu: [1]
Using TensorFlow backend.
loading model /storage/ssd/deepemhancer/production_checkpoints/deepEMhancer_tightTarget.hd5 ... DONE!
Automatic radial noise detected beyond 37.0 % of volume side
DONE!. Shape at 1 A/voxel after padding->  (384, 384, 384)
Neural net inference
  0%|                                                                                                                                                                                    | 0/441 [00:00<?, ?it/s]2023-10-20 14:43:29.681357: E tensorflow/stream_executor/cuda/cuda_blas.cc:428] failed to run cuBLAS routine: CUBLAS_STATUS_EXECUTION_FAILED
Traceback (most recent call last):
  File "/programs/x86_64-linux/deepemhancer/20220530_cu10/bin/deepemhancer", line 11, in <module>
    sys.exit(commanLineFun())
  File "/programs/x86_64-linux/deepemhancer/20220530_cu10/miniconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/deepEMhancer/exeDeepEMhancer.py", line 80, in commanLineFun
    main( ** parseArgs() )
  File "/programs/x86_64-linux/deepemhancer/20220530_cu10/miniconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/deepEMhancer/exeDeepEMhancer.py", line 73, in main
    voxel_size=boxSize, apply_postprocess_cleaning=cleaningStrengh)
  File "/programs/x86_64-linux/deepemhancer/20220530_cu10/miniconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/deepEMhancer/applyProcessVol/processVol.py", line 186, in predict
    batch_y_pred= self.model.predict_on_batch(np.expand_dims(batch_x, axis=-1))
  File "/programs/x86_64-linux/deepemhancer/20220530_cu10/miniconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/keras/engine/training.py", line 1274, in predict_on_batch
    outputs = self.predict_function(ins)
  File "/programs/x86_64-linux/deepemhancer/20220530_cu10/miniconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/programs/x86_64-linux/deepemhancer/20220530_cu10/miniconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/programs/x86_64-linux/deepemhancer/20220530_cu10/miniconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1458, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Blas SGEMM launch failed : m=262144, n=1, k=8
         [[{{node conv3d_21/convolution}}]]
  (1) Internal: Blas SGEMM launch failed : m=262144, n=1, k=8
         [[{{node conv3d_21/convolution}}]]
         [[activation_10/Identity/_609]]
0 successful operations.
0 derived errors ignored.
  0%|                                                                                                                                                                                    | 0/441 [00:17<?, ?it/s]
</pre></details>

For the tensorflow oneliner I made a new conda env with just tensorflow installed the result is this:
<pre>(tensorflow) snijderlab@Snijderlab-GPU:~$ python -c "import tensorflow as tf; print([d.name for d in tf.config.list_physical_devices('GPU')])"
2023-10-20 15:35:29.824523: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[]</pre>
Maybe I set up things wrong for this, I never really work with Python or TensorFlow in my own programming.

**Comment by rsanchezgarc** [comment]
Hi,
Can you try the oneliner with the deepEMhancer python interpreter instead?
Given your logs it should be `/programs/x86_64-linux/deepemhancer/20220530_cu10/miniconda3/envs/deepEMhancer_env/bin/python`
```
/programs/x86_64-linux/deepemhancer/20220530_cu10/miniconda3/envs/deepEMhancer_env/bin/python -c "import tensorflow as tf; print([d.name for d in tf.config.list_physical_devices('GPU')])"

```

If you don't see any device listed (as in your previous trial), then I think you should install a newer version with cuda >=11. 
Following the instructions here https://github.com/rsanchezgarc/deepEMhancer#install-from-source-option you should be able to install it without root permissions.

**Comment by douweschulte** [comment]
Thanks for providing the path, I was trying to find the correct python last time but could not figure it out. I changed the python code though, because the code you sent was not running (see first code block) but another way of doing the same returned correctly our four gpus.

<details>
<pre>
(base) snijderlab@Snijderlab-GPU:~$ /programs/x86_64-linux/deepemhancer/20220530_cu10/miniconda3/envs/deepEMhancer_env/bin/python -c "import tensorflow as tf; print([d.name for d in tf.config.list_physical_devices('GPU')])"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/programs/x86_64-linux/deepemhancer/20220530_cu10/miniconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/tensorflow/python/util/deprecation_wrapper.py", line 106, in __getattr__
    attr = getattr(self._dw_wrapped_module, name)
AttributeError: module 'tensorflow._api.v1.config' has no attribute 'list_physical_devices'
</pre>
<pre>
(base) snijderlab@Snijderlab-GPU:~$ /programs/x86_64-linux/deepemhancer/20220530_cu10/miniconda3/envs/deepEMhancer_env/bin/python -c "import tensorflow as tf; print(tf.test.gpu_device_name())"
2023-10-23 09:36:08.182258: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2023-10-23 09:36:08.212469: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3200015000 Hz
2023-10-23 09:36:08.214192: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56134d560e10 executing computations on platform Host. Devices:
2023-10-23 09:36:08.214224: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2023-10-23 09:36:08.216688: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2023-10-23 09:36:08.481615: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56134e4cf770 executing computations on platform CUDA. Devices:
2023-10-23 09:36:08.481640: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): NVIDIA RTX A4000, Compute Capability 8.6
2023-10-23 09:36:08.481644: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (1): NVIDIA RTX A4000, Compute Capability 8.6
2023-10-23 09:36:08.481648: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (2): NVIDIA RTX A4000, Compute Capability 8.6
2023-10-23 09:36:08.481652: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (3): NVIDIA RTX A4000, Compute Capability 8.6
2023-10-23 09:36:08.482842: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties:
name: NVIDIA RTX A4000 major: 8 minor: 6 memoryClockRate(GHz): 1.56
pciBusID: 0000:81:00.0
2023-10-23 09:36:08.483028: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 1 with properties:
name: NVIDIA RTX A4000 major: 8 minor: 6 memoryClockRate(GHz): 1.56
pciBusID: 0000:82:00.0
2023-10-23 09:36:08.483214: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 2 with properties:
name: NVIDIA RTX A4000 major: 8 minor: 6 memoryClockRate(GHz): 1.56
pciBusID: 0000:c1:00.0
2023-10-23 09:36:08.483392: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 3 with properties:
name: NVIDIA RTX A4000 major: 8 minor: 6 memoryClockRate(GHz): 1.56
pciBusID: 0000:c2:00.0
2023-10-23 09:36:08.483734: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2023-10-23 09:36:08.485374: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2023-10-23 09:36:08.486532: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2023-10-23 09:36:08.486722: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2023-10-23 09:36:08.488150: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2023-10-23 09:36:08.489606: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2023-10-23 09:36:08.493473: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2023-10-23 09:36:08.494658: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0, 1, 2, 3
2023-10-23 09:36:08.494682: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2023-10-23 09:36:08.495303: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-10-23 09:36:08.495313: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 1 2 3
2023-10-23 09:36:08.495316: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N Y Y Y
2023-10-23 09:36:08.495319: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 1:   Y N Y Y
2023-10-23 09:36:08.495321: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 2:   Y Y N Y
2023-10-23 09:36:08.495324: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 3:   Y Y Y N
2023-10-23 09:36:08.496116: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/device:GPU:0 with 15138 MB memory) -> physical GPU (device: 0, name: NVIDIA RTX A4000, pci bus id: 0000:81:00.0, compute capability: 8.6)
2023-10-23 09:36:08.496758: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/device:GPU:1 with 15070 MB memory) -> physical GPU (device: 1, name: NVIDIA RTX A4000, pci bus id: 0000:82:00.0, compute capability: 8.6)
2023-10-23 09:36:08.497196: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/device:GPU:2 with 15138 MB memory) -> physical GPU (device: 2, name: NVIDIA RTX A4000, pci bus id: 0000:c1:00.0, compute capability: 8.6)
2023-10-23 09:36:08.497608: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/device:GPU:3 with 15138 MB memory) -> physical GPU (device: 3, name: NVIDIA RTX A4000, pci bus id: 0000:c2:00.0, compute capability: 8.6)
/device:GPU:0
</pre></details>

**Comment by rsanchezgarc** [comment]
That is good I guess.
Can you try the following script to check if there is some problem with the installation?

Save the following lines as script.py
```
import tensorflow as tf

# Ensure that you are using TensorFlow 1.x
print(tf.__version__)

# Create a TensorFlow session
with tf.Session() as sess:
    # Specify the GPU to use
    with tf.device('/gpu:0'):  # Change to '/gpu:1' for the second GPU, etc.
        # Create a tensor and initialize it with a constant value
        a = tf.constant([1.0, 2.0, 3.0, 4.0], shape=[2, 2], name='a')
        b = tf.constant([4.0, 3.0, 2.0, 1.0], shape=[2, 2], name='b')
        
        # Perform a simple operation
        result = tf.matmul(a, b)
        
    # Run the operation
    print(sess.run(result))
```

and run it using deepEMhancer python interpreter.

**Comment by douweschulte** [comment]
This is the result:
<details><pre>
1.14.0
WARNING:tensorflow:From EMH_script.py:7: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2023-10-23 10:44:05.971848: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2023-10-23 10:44:06.035248: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties:
name: NVIDIA RTX A4000 major: 8 minor: 6 memoryClockRate(GHz): 1.56
pciBusID: 0000:81:00.0
2023-10-23 10:44:06.035437: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 1 with properties:
name: NVIDIA RTX A4000 major: 8 minor: 6 memoryClockRate(GHz): 1.56
pciBusID: 0000:82:00.0
2023-10-23 10:44:06.035607: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 2 with properties:
name: NVIDIA RTX A4000 major: 8 minor: 6 memoryClockRate(GHz): 1.56
pciBusID: 0000:c1:00.0
2023-10-23 10:44:06.035774: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 3 with properties:
name: NVIDIA RTX A4000 major: 8 minor: 6 memoryClockRate(GHz): 1.56
pciBusID: 0000:c2:00.0
2023-10-23 10:44:06.035932: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2023-10-23 10:44:06.036755: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2023-10-23 10:44:06.037516: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2023-10-23 10:44:06.037676: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2023-10-23 10:44:06.038658: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2023-10-23 10:44:06.039370: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2023-10-23 10:44:06.041580: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2023-10-23 10:44:06.042801: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0, 1, 2, 3
2023-10-23 10:44:06.051730: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2023-10-23 10:44:06.063106: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3200015000 Hz
2023-10-23 10:44:06.064676: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55c661809fb0 executing computations on platform Host. Devices:
2023-10-23 10:44:06.064715: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2023-10-23 10:44:06.312231: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55c6627a7fd0 executing computations on platform CUDA. Devices:
2023-10-23 10:44:06.312263: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): NVIDIA RTX A4000, Compute Capability 8.6
2023-10-23 10:44:06.312270: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (1): NVIDIA RTX A4000, Compute Capability 8.6
2023-10-23 10:44:06.312276: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (2): NVIDIA RTX A4000, Compute Capability 8.6
2023-10-23 10:44:06.312280: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (3): NVIDIA RTX A4000, Compute Capability 8.6
2023-10-23 10:44:06.313938: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties:
name: NVIDIA RTX A4000 major: 8 minor: 6 memoryClockRate(GHz): 1.56
pciBusID: 0000:81:00.0
2023-10-23 10:44:06.314208: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 1 with properties:
name: NVIDIA RTX A4000 major: 8 minor: 6 memoryClockRate(GHz): 1.56
pciBusID: 0000:82:00.0
2023-10-23 10:44:06.314521: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 2 with properties:
name: NVIDIA RTX A4000 major: 8 minor: 6 memoryClockRate(GHz): 1.56
pciBusID: 0000:c1:00.0
2023-10-23 10:44:06.314783: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 3 with properties:
name: NVIDIA RTX A4000 major: 8 minor: 6 memoryClockRate(GHz): 1.56
pciBusID: 0000:c2:00.0
2023-10-23 10:44:06.314827: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2023-10-23 10:44:06.314843: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2023-10-23 10:44:06.314856: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2023-10-23 10:44:06.314870: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2023-10-23 10:44:06.314883: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2023-10-23 10:44:06.314895: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2023-10-23 10:44:06.314908: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2023-10-23 10:44:06.316914: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0, 1, 2, 3
2023-10-23 10:44:06.316959: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2023-10-23 10:44:06.317957: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-10-23 10:44:06.317973: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 1 2 3
2023-10-23 10:44:06.317982: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N Y Y Y
2023-10-23 10:44:06.317990: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 1:   Y N Y Y
2023-10-23 10:44:06.317998: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 2:   Y Y N Y
2023-10-23 10:44:06.318005: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 3:   Y Y Y N
2023-10-23 10:44:06.319335: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15138 MB memory) -> physical GPU (device: 0, name: NVIDIA RTX A4000, pci bus id: 0000:81:00.0, compute capability: 8.6)
2023-10-23 10:44:06.320095: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 15076 MB memory) -> physical GPU (device: 1, name: NVIDIA RTX A4000, pci bus id: 0000:82:00.0, compute capability: 8.6)
2023-10-23 10:44:06.320846: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 15138 MB memory) -> physical GPU (device: 2, name: NVIDIA RTX A4000, pci bus id: 0000:c1:00.0, compute capability: 8.6)
2023-10-23 10:44:06.321411: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 15138 MB memory) -> physical GPU (device: 3, name: NVIDIA RTX A4000, pci bus id: 0000:c2:00.0, compute capability: 8.6)
[[ 8.  5.]
 [20. 13.]]
</pre></details>

**Comment by rsanchezgarc** [comment]
Tensorflow seems to work. I wasn't expecting this. Generally speaking, this would mean that you got out of GPU memory, but with batch size 1 and  `export TF_FORCE_GPU_ALLOW_GROWTH='true'` it should not happen unless you have other processes using the GPUs, but I assume that you have checked it with `nvidia-smi`. I also read here https://stackoverflow.com/questions/59848008/tensorflow-blas-gemm-launch-failed
that removing your `~/.nv` cache can help. However, I am afraid that I still believe that the easiest will be to install a newer deepEMhancer version that comes with a newer CUDA version. It should take a few minutes to do so.
Sorry for not being more helpful.

**Comment by douweschulte** [comment]
Sorry for the late reply, but with cuda 11 it seems to work. Thanks for helping in figuring out the issue!
