### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'layer'

### ISSUE THREAD

**Issue by zfb601** [rsanchezgarc/deepEMhancer#39]
updating environment to select gpu: [0]
Using TensorFlow backend.
loading model /home/lab2/.local/share/deepEMhancerModels/production_checkpoints/                                                                                                deepEMhancer_wideTarget.hd5 ... Traceback (most recent call last):
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/bin/deepemhancer", line 11, i                                                                                                n <module>
    sys.exit(commanLineFun())
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/d                                                                                                eepEMhancer/exeDeepEMhancer.py", line 80, in commanLineFun
    main( ** parseArgs() )
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/d                                                                                                eepEMhancer/exeDeepEMhancer.py", line 70, in main
    predictor= AutoProcessVol(checkpoint_fname, gpuIds= gpuIds, batch_size= batc                                                                                                h_size)
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/d                                                                                                eepEMhancer/applyProcessVol/processVol.py", line 31, in __init__
    self.model = load_model(model_fname, nGpus=nGpus )
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/d                                                                                                eepEMhancer/utils/loadModel.py", line 19, in load_model
    model= load_model(checkpoint_fname, custom_objects=custom_objects )
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/k                                                                                                eras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/k                                                                                                eras/engine/saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/k                                                                                                eras/engine/saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/k                                                                                                eras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/k                                                                                                eras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/k                                                                                                eras/engine/network.py", line 1032, in from_config
    process_node(layer, node_data)
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/k                                                                                                eras/engine/network.py", line 991, in process_node
    layer(unpack_singleton(input_tensors), **kwargs)
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/t                                                                                                ensorflow/python/keras/engine/base_layer.py", line 663, in __call__
    inputs, outputs, args, kwargs)
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/t                                                                                                ensorflow/python/keras/engine/base_layer.py", line 1708, in _set_connectivity_me                                                                                                tadata_
    input_tensors=inputs, output_tensors=outputs, arguments=kwargs)
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/t                                                                                                ensorflow/python/keras/engine/base_layer.py", line 1795, in _add_inbound_node
    input_tensors)
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/t                                                                                                ensorflow/python/util/nest.py", line 515, in map_structure
    structure[0], [func(*x) for x in entries],
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/t                                                                                                ensorflow/python/util/nest.py", line 515, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/t                                                                                                ensorflow/python/keras/engine/base_layer.py", line 1794, in <lambda>
    inbound_layers = nest.map_structure(lambda t: t._keras_history.layer,
AttributeError: 'tuple' object has no attribute 'layer'
(deepEMhancer_env) lab2@lab2-M12SWA-TF:~$ deepemhancer -i /media/lab2/LL61_20240611/MPXV_LL61_20240516_20240612_300kV/CS-mpxv-20240516-20240612-300kv/J76/J76_001_volume_map_half_A.mrc -i2 /media/lab2/LL61_20240611/MPXV_LL61_20240516_20240612_300kV/CS-mpxv-20240516-20240612-300kv/J76/J76_001_volume_map_half_B.mrc -o /media/lab2/LL61_20240611/MPXV_LL61_20240516_20240612_300kV/CS-mpxv-20240516-20240612-300kv/J84/J84_map_sharp.mrc -g 0 -p wideTarget
updating environment to select gpu: [0]
Using TensorFlow backend.
loading model /home/lab2/.local/share/deepEMhancerModels/production_checkpoints/deepEMhancer_wideTarget.hd5 ... Traceback (most recent call last):
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/bin/deepemhancer", line 11, in <module>
    sys.exit(commanLineFun())
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/deepEMhancer/exeDeepEMhancer.py", line 80, in commanLineFun
    main( ** parseArgs() )
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/deepEMhancer/exeDeepEMhancer.py", line 70, in main
    predictor= AutoProcessVol(checkpoint_fname, gpuIds= gpuIds, batch_size= batch_size)
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/deepEMhancer/applyProcessVol/processVol.py", line 31, in __init__
    self.model = load_model(model_fname, nGpus=nGpus )
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/deepEMhancer/utils/loadModel.py", line 19, in load_model
    model= load_model(checkpoint_fname, custom_objects=custom_objects )
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/keras/engine/saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/keras/engine/saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/keras/engine/network.py", line 1032, in from_config
    process_node(layer, node_data)
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/keras/engine/network.py", line 991, in process_node
    layer(unpack_singleton(input_tensors), **kwargs)
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 663, in __call__
    inputs, outputs, args, kwargs)
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1708, in _set_connectivity_metadata_
    input_tensors=inputs, output_tensors=outputs, arguments=kwargs)
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1795, in _add_inbound_node
    input_tensors)
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/tensorflow/python/util/nest.py", line 515, in map_structure
    structure[0], [func(*x) for x in entries],
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/tensorflow/python/util/nest.py", line 515, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "/home/lab2/anaconda3/envs/deepEMhancer_env/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1794, in <lambda>
    inbound_layers = nest.map_structure(lambda t: t._keras_history.layer,
AttributeError: 'tuple' object has no attribute 'layer'

**Comment by zfb601** [comment]
Install from Anaconda cloud:
Requires anaconda/miniconda, that can be obtained from hhttps://[www.anaconda.com/products/individual](http://www.anaconda.com/products/individual). This option will install the legacy version of deepEMhancer that uses Tensorflow 1.14 and CUDA 10.2. It does not work well in some of the newer GPU cards.

Create a fresh conda environment
conda create -n deepEMhancer_env python=3.6
Activate the environment. You always need to activate the environment before executing deepEMhancer
conda activate deepEMhancer_env
Install deepEMhancer
conda install deepEMhancer -c rsanchez1369 -c anaconda -c conda-forge

**Comment by zfb601** [comment]
conda list keras
# packages in environment at /home/lab2/anaconda3/envs/deepEMhancer_env:
#
# Name                    Version                   Build  Channel
keras                     2.2.4                         0    anaconda
keras-applications        1.0.8                      py_1    anaconda
keras-base                2.2.4                    py36_0    anaconda
keras-contrib             2.0.8                    pypi_0    pypi
keras-preprocessing       1.1.2              pyhd3eb1b0_0    anaconda
keras-radam               0.12.0                   pypi_0    pypi

**Comment by zfb601** [comment]
conda list tensorflow
# packages in environment at /home/lab2/anaconda3/envs/deepEMhancer_env:
#
# Name                    Version                   Build  Channel
tensorflow                1.14.0          gpu_py36h3fb9ad6_0    anaconda
tensorflow-base           1.14.0          gpu_py36he45bfe2_0    anaconda
tensorflow-estimator      1.14.0                     py_0    anaconda
tensorflow-gpu            1.14.0               h0d30ee6_0    anaconda

**Comment by rsanchezgarc** [comment]
Hi,
The error you see is because you are using the deepEMhancer version that employs tensorflow v1, but the program is trying to load the models for version v2. If you download the models for your current installation (https://zenodo.org/records/7432763), then it should work.

You can do it with the following commands
```
wget https://zenodo.org/records/7432763/files/deepEMhancerModels_tf1.zip
unzip deepEMhancerModels_tf1.zip
# This will unzip a folder called production_checkpoints
# Now you can run deepEMhancer telling where you downloaded the checkpoins
TF_FORCE_GPU_ALLOW_GROWTH='true' deepemhancer --i input.mrc --o out.mrc --deepLearningModelPath  production_checkpoints/ 
# You can copy production_checkpoints to ~/.local/share/deepEMhancerModels/ to let  deepEMhancer find your models automatically
```

**Comment by rsanchezgarc** [comment]
In addition, I just have updated the repository documentation to point out that if you create an environment with  python=3.10 version, and use the conda install option, then you will get the tensorflow v2 version of deepEMhancer, so the default checkpoints will work

**Comment by zfb601** [comment]
Hi,

Thanks for your suggestion. I simply reinstalled from source option. Now it works all fine.

Install from source option:
The best option to keep you updated. Currently, it uses Tensorflow version 2.10 and CUDA>11.2. This option works well in the new Nvidia GPUs (Ampere) but is should also work for the older versions. See other installation options if you want to install the original version of deepEMhancer that does NOT work in Nvidia Ampere GPUs
Requires anaconda/miniconda, that can be obtained from https://www.anaconda.com/products/individual

Steps:

Clone this repository and cd inside
git clone https://github.com/rsanchezgarc/deepEMhancer
cd deepEMhancer
Create a conda environment with the required dependencies
conda env create -f deepEMhancer_env.yml  -n deepEMhancer_env
Activate the environment. You always need to activate the environment before executing deepEMhancer
conda activate deepEMhancer_env
Set CUDA LD_LIBRARY_PATH
conda env config vars set LD_LIBRARY_PATH=${CONDA_PREFIX}/lib/python3.9/site-packages/nvidia/cudnn/lib:${CONDA_PREFIX}/lib/:$LD_LIBRARY_PATH
conda activate deepEMhancer_env #To make the changes effective
Install deepEMhancer
python -m pip install . --no-deps
Download our deep learning models
deepemhancer --download
Ready! Do not forget to activate the environment for future usages. For a complete help use:
deepemhancer -h
Optionally, you can remove the folder, since deepemhancer will be available anywhere once you activate the environment
