### ISSUE TITLE
support for TF2/CUDA 11?

### ISSUE THREAD

**Issue by olibclarke** [rsanchezgarc/deepEMhancer#8]
Hi,

We have a new GPU with RTX-3090s, which require CUDA 11.1 or later. Will DeepEMhancer work on this system? I am assuming not because it uses CUDA 10/TF 1 - so if not, is there a possibility of CUDA 11.x support in the future?

Cheers
Oli

**Comment by rsanchezgarc** [comment]
Hi Oli,

DeepEMhancer uses CUDA 10  but it should be compatible with your card (they are generally retrocompatible). You should not care about which CUDA version you have installed, DeepEMhancer should install its own CUDA. So please, try to install it normally and execute it. If it turns out it won't work, we will work on fixing it.


Thank you very much.

Ruben

**Comment by rui--zhang** [comment]
Hi, I found deepEMhancer cannot launch on my workstation with 8x GeForce RTX 3090 GPUs and CUDA 11.1.
It hangs at 0% progress after loading the model (see below), and no GPU processors are running according to "nvidia-smi"
(deepEMhancer_env) zhangrui@sp.wustl.edu:
updating environment to select gpu: [0, 1, 2, 3, 4, 5, 6, 7]
Using TensorFlow backend.
loading model /home/zhangrui/.local/share/deepEMhancerModels/production_checkpoints/deepEMhancer_highRes.hd5 ... DONE!
DONE!. Shape at 1.00 A/voxel after padding->  (688, 688, 688)
Neural net inference
  0%|                                                                                                                                                            | 1/1600 [00:00<00:00, 15141.89it/s]

Can you please look into this issue?
Thanks!
Rui

**Comment by rsanchezgarc** [comment]
Hi Rui. 

Thanks a lot for your report. Have you tried using only 1 GPU (e.g. -g 0) and no GPU -g -1?

Ruben

**Comment by rui--zhang** [comment]
Testing with 1 GPU showed very similar behavior: hangs at the first steps.
I just noticed the GPU0 memory is actually fully loaded, maybe this is the problem?
Is there a way to limit the memory usage per GPU?

zhangrui@sp:~$ nvidia-smi
Fri Apr  9 14:47:48 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.45.01    Driver Version: 455.45.01    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3090    Off  | 00000000:1B:00.0 Off |                  N/A |
| 30%   40C    P2   105W / 350W |  23279MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 3090    Off  | 00000000:1C:00.0 Off |                  N/A |
| 30%   36C    P0   102W / 350W |      0MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 3090    Off  | 00000000:1D:00.0 Off |                  N/A |
| 30%   38C    P0   107W / 350W |      0MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 3090    Off  | 00000000:1E:00.0 Off |                  N/A |
| 30%   37C    P0   114W / 350W |      0MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  GeForce RTX 3090    Off  | 00000000:B2:00.0 Off |                  N/A |
| 30%   36C    P0   110W / 350W |      0MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  GeForce RTX 3090    Off  | 00000000:B3:00.0 Off |                  N/A |
| 30%   36C    P0   103W / 350W |      0MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  GeForce RTX 3090    Off  | 00000000:B4:00.0 Off |                  N/A |
| 30%   35C    P0   108W / 350W |      0MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   7  GeForce RTX 3090    Off  | 00000000:B5:00.0 Off |                  N/A |
| 30%   33C    P0    68W / 350W |      0MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

**Comment by rsanchezgarc** [comment]
Hi Rui,

By default, Tensorflow allocates all available memory, so it shouldn't be the problem. Last trial, does it work when you use CPU only mode ( -g -1)? If it does work it is probably something related to CUDA

Ruben

**Comment by rui--zhang** [comment]
Hmm, with -g -1, it seems to be stuck at 0% as well (I should say it progresses extremely slow, from 0/1600 to 1/1600).  "top" command shows deepemhancer is using 16 CPUs.
zhangrui@sp:~$./z_deepEM.sh
updating environment to select gpu: None
Using TensorFlow backend.
2021-04-10 20:05:35.052958: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
loading model /home/zhangrui/.local/share/deepEMhancerModels/production_checkpoints/deepEMhancer_highRes.hd5 ... DONE!
DONE!. Shape at 1.00 A/voxel after padding->  (688, 688, 688)
Neural net inference
  0%|                                                                                                              | 1/1600 [04:40<124:35:36, 280.51s/it]

**Comment by rsanchezgarc** [comment]
Hi Rui,

CPU only is very slow, so I am not surprised. Could you double check if when using GPUS CPU mode is used instead (monitor it using top again please)? (It is the behavior I would expect if GPUs are not available or, as it seems here, not compatible),

Independently, it seems I have to rewrite the program to make it work with Tensorflow 2.4+.
I will let you know when I have a prototipe.

Thank you very much.

Ruben

**Comment by rui--zhang** [comment]
Hi, when specifying -g 0, top command shows 1 CPU is running, which seems to be normal. 
And "nvidia-smi" indicates some deepEM job is assigned to GPU.

**Comment by rsanchezgarc** [comment]
@rui--zhang and @olibclarke . Hi I've just implemented a prototype using tensorflow version 2 (tf2). It is in branch "tf". I would really appreciate if you can install it and try it.

To do so :
1) Download the repository if you don't have done it yet (`git clone https://github.com/rsanchezgarc/deepEMhancer`)
2) Go to the repository `cd deepEMhancer`
3) Bring the changes `git fetch `
4) Switch branch `git checkout tf2`
5) Install the new environment. In principle, you can try to update the current deepEMhancer_env using `conda update tensorflow` etc. But I have prepared a new .yml file to install it from scratch. To do so, you only need to do `conda env create -f alternative_installation/deepEMhancer_tf2.env.yml` . You may want to specificity an environment name using -n envName
6) Modify the original models to be used with tf2, `python alternative_installation/convert_models_to_tf2.py ` (only affects the models in the default location) or  `python alternative_installation/convert_models_to_tf2.py path/where/models/are` if you want to specify the directory where you downloaded the models.

I guess it should be enough.

Thank you very much

Ruben

**Comment by rui--zhang** [comment]
OK. Thanks! Will try it now!

**Comment by rui--zhang** [comment]
Hi, I am getting this error message:

(deepEMhancer_env2) zhangrui@sp:/data/deepEM_dir/test/$ ./z_deepEM.sh
updating environment to select gpu: [0, 1, 2, 3, 4, 5, 6, 7]
loading model /home/zhangrui/.local/share/deepEMhancerModels/production_checkpoints/deepEMhancer_highRes.hd5 ... Traceback (most recent call last):
  File "/home/zhangrui/.conda/envs/deepEMhancer_env2/bin/deepemhancer", line 8, in <module>
    sys.exit(commanLineFun())
  File "/home/zhangrui/.conda/envs/deepEMhancer_env2/lib/python3.8/site-packages/deepEMhancer/exeDeepEMhancer.py", line 80, in commanLineFun
    main( ** parseArgs() )
  File "/home/zhangrui/.conda/envs/deepEMhancer_env2/lib/python3.8/site-packages/deepEMhancer/exeDeepEMhancer.py", line 70, in main
    predictor= AutoProcessVol(checkpoint_fname, gpuIds= gpuIds, batch_size= batch_size)
  File "/home/zhangrui/.conda/envs/deepEMhancer_env2/lib/python3.8/site-packages/deepEMhancer/applyProcessVol/processVol.py", line 31, in __init__
    self.model = load_model(model_fname, nGpus=nGpus )
  File "/home/zhangrui/.conda/envs/deepEMhancer_env2/lib/python3.8/site-packages/deepEMhancer/utils/loadModel.py", line 9, in load_model
    __, codes = retrieveParamsFromHd5(checkpoint_fname,  [], ['code/custom_objects'])
  File "/home/zhangrui/.conda/envs/deepEMhancer_env2/lib/python3.8/site-packages/deepEMhancer/utils/loadModel.py", line 93, in retrieveParamsFromHd5
    exec(codeStr, env)  # normFun is in the code
  File "<string>", line 3
    import tensorflow as tf
    ^
IndentationError: unexpected indent

**Comment by rsanchezgarc** [comment]
Ups, Copy paste error. It should work know.

Just update changes (`git pull`) and reinstall deepemhancer as in the previous message. To remove  the environment `conda env remove -n NAME_OF_ENVIRON` Please notice that I have updated it since I forgot the last step

Thank you very much.

Ruben

**Comment by rui--zhang** [comment]
Now it seems to be working fine! I will compare the results and let you know!

**Comment by rui--zhang** [comment]
Unfortunately, the result seems to be completely wrong... (although it only took ~20 mins to finish a 512 box with 8x 3090 cards, it will take ~35 mins for 8x 1080Ti cards).
Can you spot anything wrong?

(deepEMhancer_env2) zhangrui@sp:/data/deepEM_dir/test$ ./z_deepEM.sh
updating environment to select gpu: [0, 1, 2, 3, 4, 5, 6, 7]
loading model /home/zhangrui/.local/share/deepEMhancerModels/production_checkpoints/deepEMhancer_highRes.hd5 ... Model reset
DONE!
/home/zhangrui/.conda/envs/deepEMhancer_env2/lib/python3.8/site-packages/deepEMhancer/applyProcessVol/processVol.py:115: FutureWarning: skimage.util.pad is deprecated and will be removed in version 0.19. Please use numpy.pad instead.
  x_pad = pad(x, paddingValues, mode="wrap")
DONE!. Shape at 1.00 A/voxel after padding->  (688, 688, 688)
Neural net inference
  8%|████████                                                                                           | 131/1600 [02:18<20:50,  1.18it/s]

**Comment by rsanchezgarc** [comment]
Hi,

At least it run. By totally wrong, you mean that you are getting a volume that is clarly incorrect?

Regarding GPU usage, I wouldn't be surprised if 8 GPUs turn out to be too many. I have only tried up to 4, so adding more could result in severe comunication overheads. Did you monitor CPU usage during execution using nvidia-smi. If GPU usage is too low, chances are that the batch size is too small for the amount of GPUs you have and thus, it could be faster if you increase the batch size. By default is 8, so trying 32 or even 64 could improve things.

Thanks for your help. It is being very useful.

Ruben

**Comment by rsanchezgarc** [comment]
Bug spotted and fixed!

"Model reset" message was a great hint.

I am afraid of being wrong but I really think this time is going to work.

Many thanks

Ruben

**Comment by rui--zhang** [comment]
Now the result seems to be fine! And with -b 32 it only takes ~17 mins for a 512 box.
Thank you so much for developing such a wonderful tool! It plays critical role in all my ongoing projects.

**Comment by alburse** [comment]
Cuda11 works for us on 3090s. Just one clarification to your guide here. 
You need to run "python alternative_installation/convert_models_to_tf2.py" this command after installing deepemhancer.

**Comment by rsanchezgarc** [comment]
@alburse Thanks for confirming it works and for your comments!
 I will update the README file as soon as I finish a couple of additional details. 
Regarding the default model path, I am opening an issue for that

**Comment by priiteek** [comment]
I couldn't get deepEMhancer running on my workstation by following the TF2 installation instructions. Everything installed normally and it seemed to detect the GPUs, but when running deepEMhancer, GPUs were not utilized (according to nvidia-smi) and progress was very slow, meaning it fell back to CPU. It turns out the problem is in cudatoolkit-11.0.221.

My system is:
CentOS 7; 2x GeForce RTX 3090
Nvidia Driver Version: 460.32.03
CUDA Version: 11.2

Checked if tensorflow works
`python -c "from tensorflow.python.client import device_lib; print(device_lib.list_local_devices())"`
and got
`Could not load dynamic library 'libcublas.so.11'; dlerror: /data/software/miniconda3/envs/deepemhancer/bin/../lib/libcublas.so.11: undefined symbol: free_gemm_select`

Found that the same problem has been reported with pytorch and cudatoolkit-11.0.221, which is the version that is currently provided by conda. The fix was to update to cudatoolkit-11.0.3:
`conda install -c conda-forge cudatoolkit=11.0.3`

I can confirm that deepEMhancer works on GPUs after running the update.

**Comment by N-Bogdanovic-85** [comment]
Hello, 

DeepEMhancer used to work for me, but it suddenly started experiencing the error shown below. I tried the new update however it is still the same. Also, it does not run at all on 8(4) x A6000 with 46 GB RAM each, while it used to run normally on 4x 2080Ti (11 GB GRAM each) and 4x A100 (32 GB GRAM each).

Here is the error:

./Map_sharpen_4gpu_wide_hires.sh
updating environment to select gpu: [1, 2, 3, 0]
loading model /home/nxb318/.local/share/deepEMhancerModels/production_checkpoints/deepEMhancer_highRes.hd5 ... DONE!
Automatic radial noise detected beyond 40 % of volume side
/home/software/anaconda3/envs/deepEMhancer_env_tf2/lib/python3.8/site-packages/deepEMhancer/applyProcessVol/processVol.py:115: FutureWarning: skimage.util.pad is deprecated and will be removed in version 0.19. Please use numpy.pad instead.
  x_pad = pad(x, paddingValues, mode="wrap")
DONE!. Shape at 1.00 A/voxel after padding->  (448, 448, 448)
Neural net inference
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 625/625 [14:44<00:00,  1.41s/it]
2021-11-04 15:21:29.825083: F ./tensorflow/core/kernels/conv_2d_gpu.h:1019] Non-OK-status: GpuLaunchKernel( SwapDimension1And2InTensor3UsingTiles<T, kNumThreads, kTileSize, kTileSize, conjugate>, total_tiles_count, kNumThreads, 0, d.stream(), input, input_dims, output) status: Internal: invalid configuration argument
./Map_sharpen_4gpu_wide_hires.sh: line 3: 29085 Aborted                 (core dumped) TF_FORCE_GPU_ALLOW_GROWTH='true' deepemhancer -p highRes --cleaningStrengh 0.2 -g 1,2,3,0 -b 6 --i *A.mrc -i2 *B.mrc --o map_highRes.mrc

I also tried with  TF_FORCE_GPU_ALLOW_GROWTH='false' to disable dynamic memory assignment and -b 4 however the same error pops up. Is there any workaround? I love deepEMhancer and it gave a really nice detergent belt removal! I'd like to see that happen for my new EM map. 

Thank you in advance.

**Comment by rsanchezgarc** [comment]
Hi @N-Bogdanovic-85 

Could you check if your tensorflow installation works?

```
conda activate YOUR_ENVIRONMENT_NAME
 python -c "from tensorflow.python.client import device_lib; print(device_lib.list_local_devices())"
```

If it is not the case, it probably needs re-installation. Chances are that there is a mismatch between the cuda version / tensorflow version / cudnn version.  Could you paste your environment packages (`conda env export`)?

**Comment by N-Bogdanovic-85** [comment]
Hi @rsanchezgarc 
Thank you for the reply. TF seems to be working on all 3 machines and the output of them all is in the text file linked below. It seems to be talking to GPUs properly, but I am not the expert there. Also, you can see my conda envs in the link. Please take note that my priority is machine number 3, which currently has the previous version of deepEMhancer featured on the main page, it does not have TF2. 

https://drive.google.com/file/d/1NYC0rMUAV1tmVBeresop9yxCv653UiGW/view?usp=sharing, https://drive.google.com/file/d/1ywLVtQJKTaE_WJ6PyLFhHOXtuw4qdFYe/view?usp=sharing

All your help is greatly appreciated.

Thank you and regards

**Comment by rsanchezgarc** [comment]
HI @N-Bogdanovic-85 

The versions seem since you are able to run ` python -c "from tensorflow.python.client import device_lib; print(device_lib.list_local_devices())"`. However, it does not totally rule out problems with respect to GPU compatibility

The first thing to try would be to run it using only one GPU (https://stackoverflow.com/questions/59068494/program-crashed-in-the-last-step-in-test-tensorflow-gpu-2-0-0). If it does work on a single GPU, then try batch size equal to 1 and multiple GPUs, and finally, a batch size divisible by the number of subcubes contained in the map, which in your case is 15625 (len(range(0, 448- (64 - 1), 64//4))**3). If you are able to run it in this way, then we can blame Tensorflow for that and I will add a new section to the troubleshooting.

If this won't solve it, I would try to install TensorFlow 2.5 or 2.6 (and their corresponding cuda and cudnn versions) instead and see what happens.

I hope it helps!

**Comment by N-Bogdanovic-85** [comment]
Hi @rsanchezgarc 

I am trying it now. It seems it is running fine on 1 GPU, comparably slower. Terminal shows 3 progress bars simultaneously, so I am not sure if that is an artifact. The run was completed successfully but I lost half of the map. I guess the cleaningStrengh 0.2 for the high-res model was too high in my case. Multi GPU (-g 1, 2, 3, 0) and batch size  (-b 1) did not work. The same error popped up.  

./Map_sharpen_4gpu_wide_hires.sh
updating environment to select gpu: [1, 2, 3, 0]
loading model /home/nxb318/.local/share/deepEMhancerModels/production_checkpoints/deepEMhancer_wideTarget.hd5 ... DONE!
Automatic radial noise detected beyond 40 % of volume side
/home/nxt193/software/anaconda3/envs/deepEMhancer_env_tf2/lib/python3.8/site-packages/deepEMhancer/applyProcessVol/processVol.py:115: FutureWarning: skimage.util.pad is deprecated and will be removed in version 0.19. Please use numpy.pad instead.
  x_pad = pad(x, paddingValues, mode="wrap")
DONE!. Shape at 1.00 A/voxel after padding->  (448, 448, 448)
Neural net inference
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 625/625 [19:40<00:00,  1.89s/it]
2021-11-04 19:55:29.070171: F ./tensorflow/core/kernels/conv_2d_gpu.h:1019] Non-OK-status: GpuLaunchKernel( SwapDimension1And2InTensor3UsingTiles<T, kNumThreads, kTileSize, kTileSize, conjugate>, total_tiles_count, kNumThreads, 0, d.stream(), input, input_dims, output) status: Internal: invalid configuration argument
./Map_sharpen_4gpu_wide_hires.sh: line 2: 33323 Aborted                 (core dumped) TF_FORCE_GPU_ALLOW_GROWTH='true' deepemhancer -p wideTarget -g 1,2,3,0 --cleaningStrengh 0.1 -b 1 --i map_half_A.mrc -i2 map_half_B.mrc --o map_wide_target.mrc

However, it has worked with TF_FORCE_GPU_ALLOW_GROWTH='true' deepemhancer -g 1,2,3,0 --cleaningStrengh 0.2 **--batch_size 25** -m mask.mrc --i map_half_A.mrc -i2 map_half_B.mrc --o map_tightTarget_masked.mrc

What would be the explanation that it now works? (machine number 1) The 15625 is divisible by 5, 25, 625 i guess...

Thank you for the help you have provided promptly!
